name: qr_code_dart_decoder
description: "A Dart package for decoding QR codes and other barcode formats using the ZXing library"
version: 0.0.3
homepage: https://github.com/RafaelBarbosatec/qr_code_dart_scan/tree/main/packages/qr_code_dart_decoder

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  zxing_lib: ^1.1.2
  image: ^4.1.6

dev_dependencies:
  test: ^1.19.2
  flutter_lints: ^2.0.0