name: qr_code_dart_decoder
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  zxing_lib: ^1.1.2
  image: ^4.1.6

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  flutter_lints: ^2.0.0