name: qr_code_dart_scan
description: A QR code scanner that works on both iOS and Android using dart decoder.
version: 0.9.4
homepage: https://github.com/RafaelBarbosatec/qr_code_dart_scan

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0
  zxing_lib: ^1.1.2
  image: ^4.1.6
  camera_platform_interface: ^2.7.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter: