name: qr_code_dart_scan
description: A QR code scanner that works on both iOS and Android using dart decoder.
version: 0.9.11
homepage: https://github.com/RafaelBarbosatec/qr_code_dart_scan

environment:
  sdk: ">=2.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.11.0
  zxing_lib: ^1.1.2
  image: ^4.5.1
  camera_platform_interface: ^2.7.3
  camera_android_camerax: ^0.6.10+1
  equatable: ^2.0.5
  qr_code_dart_decoder: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: