name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened,ready_for_review,synchronize]

jobs:
  tests:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Intall dart
        uses: dart-lang/setup-dart@v1

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get packages
        run: |
          flutter pub get
          cd packages/qr_code_dart_decoder
          flutter pub get

      - name: Check lint errors
        run: |
          flutter analyze .
          cd packages/qr_code_dart_decoder
          flutter analyze .

      - name: Run tests
        run: |
          cd packages/qr_code_dart_decoder
          flutter test